
name: Build & Release

on:
  push:
    branches: 
      - "main"
    paths-ignore: 
      - "README.md"
      # - ".github/**"
  pull_request:
    types:
      - closed

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21.x'
    - name: Show ref_name
      run: echo ${{ github.ref_name }}

    # - name: Build Linux
    #   run: go build -o ./bin/linux/tfmodule_linux ./...
      
    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o ./bin/win/tfmodule_win.exe ./...
      
    - name: Build MacOS
      run: GOOS=darwin GOARCH=amd64 go build -o ./bin/mac/tfmodule_mac ./...
      
    - name: Upload Go results
      uses: actions/upload-artifact@v3
      with:
        name: Go-results
        path: ./bin/
      
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        #files: |
          #./bin/mac/tfmodule_${{github.ref_name}}_mac
          #./bin/win/tfmodule_${{github.ref_name}}_win.exe
          #./bin/linux/tfmodule_${{github.ref_name}}_linux
        files: |
          ./bin/mac/tfmodule_${{github.ref_name}}_mac
          ./bin/win/tfmodule_${{github.ref_name}}_win.exe
          ./bin/linux/tfmodule_${{github.ref_name}}_linux
    
